using Memux.Core.Models;

namespace Memux.Actions;

/// <summary>
/// Executes action queues generated by skills
/// Records actions for pattern detection
/// </summary>
public class ActionExecutor
{
    private readonly ControllerInput _controller = new();
    private readonly List<string> _recentActions = new();
    private readonly object _lock = new();
    
    /// <summary>
    /// Event fired when an action sequence is recorded
    /// Used for pattern detection and meta-skill generation
    /// </summary>
    public event EventHandler<ActionSequenceEventArgs>? ActionSequenceRecorded;
    
    public async Task<ExecutionResult> ExecuteAsync(ActionQueue queue, PerceptionState currentState)
    {
        var startTime = DateTime.UtcNow;
        var executedActions = new List<string>();
        
        try
        {
            foreach (var action in queue.Actions)
            {
                // Apply delay before action
                if (action.DelayBeforeMs > 0)
                {
                    await Task.Delay(action.DelayBeforeMs);
                }
                
                // Execute action based on type
                switch (action.Type)
                {
                    case ActionType.KeyPress:
                        if (action.Key != null)
                        {
                            KeyboardInput.PressKey(action.Key, action.DurationMs);
                            executedActions.Add($"Key({action.Key})");
                        }
                        break;
                    
                    case ActionType.ButtonPress:
                        if (action.Button != null)
                        {
                            _controller.PressButton(action.Button, action.DurationMs);
                            executedActions.Add($"Btn({action.Button})");
                        }
                        break;
                    
                    case ActionType.StickMovement:
                        if (action.Stick != null)
                        {
                            _controller.SetStick(action.Stick, action.X, action.Y, action.DurationMs);
                            executedActions.Add($"Stick({action.Stick},{action.X},{action.Y})");
                        }
                        break;
                    
                    case ActionType.Wait:
                        await Task.Delay(action.DurationMs);
                        executedActions.Add($"Wait({action.DurationMs})");
                        break;
                    
                    case ActionType.PerceptionCheck:
                        if (action.PerceptionCondition != null)
                        {
                            bool conditionMet = await WaitForConditionAsync(
                                action.PerceptionCondition,
                                action.TimeoutMs);
                            
                            if (!conditionMet)
                            {
                                return new ExecutionResult
                                {
                                    Success = false,
                                    ErrorMessage = "Perception check timeout",
                                    ExecutionTimeMs = (int)(DateTime.UtcNow - startTime).TotalMilliseconds,
                                    ExecutedActions = executedActions
                                };
                            }
                            executedActions.Add("Check(passed)");
                        }
                        break;
                }
            }
            
            // Record action sequence for pattern detection
            RecordActionSequence(queue.SkillName ?? "Unknown", executedActions);
            
            return new ExecutionResult
            {
                Success = true,
                ExecutionTimeMs = (int)(DateTime.UtcNow - startTime).TotalMilliseconds,
                ExecutedActions = executedActions
            };
        }
        catch (Exception ex)
        {
            return new ExecutionResult
            {
                Success = false,
                ErrorMessage = ex.Message,
                ExecutionTimeMs = (int)(DateTime.UtcNow - startTime).TotalMilliseconds,
                ExecutedActions = executedActions
            };
        }
    }
    
    private async Task<bool> WaitForConditionAsync(
        Func<PerceptionState, bool> condition,
        int timeoutMs)
    {
        // TODO: Implement actual perception checking
        // For now, just wait and return true
        await Task.Delay(Math.Min(timeoutMs, 1000));
        return true;
    }
    
    private void RecordActionSequence(string skillName, List<string> actions)
    {
        lock (_lock)
        {
            _recentActions.AddRange(actions);
            
            // Keep only recent actions (last 100)
            if (_recentActions.Count > 100)
            {
                _recentActions.RemoveRange(0, _recentActions.Count - 100);
            }
        }
        
        // Fire event for pattern detection
        ActionSequenceRecorded?.Invoke(this, new ActionSequenceEventArgs
        {
            SkillName = skillName,
            Actions = new List<string>(actions),
            Timestamp = DateTime.UtcNow
        });
    }
    
    /// <summary>
    /// Get recent action history for pattern detection
    /// </summary>
    public List<string> GetRecentActions(int count = 20)
    {
        lock (_lock)
        {
            return _recentActions.TakeLast(count).ToList();
        }
    }
}

public class ExecutionResult
{
    public bool Success { get; set; }
    public string? ErrorMessage { get; set; }
    public int ExecutionTimeMs { get; set; }
    public List<string> ExecutedActions { get; set; } = new();
}

public class ActionSequenceEventArgs : EventArgs
{
    public string SkillName { get; set; } = string.Empty;
    public List<string> Actions { get; set; } = new();
    public DateTime Timestamp { get; set; }
}

