<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Memux.Core\Memux.Core.csproj" />
    <ProjectReference Include="..\Memux.Skills\Memux.Skills.csproj" />
    <ProjectReference Include="..\Memux.Composer\Memux.Composer.csproj" />
  </ItemGroup>

</Project>

